# Generated by Django 4.1.7 on 2023-04-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(default='2023-01-01', verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.TimeField(default='11:45:23', verbose_name='زمان'),
        ),
    ]
